### PR TITLE
support for PySide6/QT6

### PR DESCRIPTION
**Pull request by psifertex**
Needed for dev or stable builds newer than 2846. Tested backward compatible as well.

### CODE REVIEW

**Comment by PistonMiner** [comment]
Thanks for your contribution!

Are you sure this is backwards compatible? I get a `ModuleNotFoundError` when trying to run this on `2.4.2846`.
In general I don't think the construct `import X as Y` followed by `from Y import Z` is actually a working construct in Python. AFAIK the first statement creates an object, which isn't something you can then use as the module name in the following import statement.

I think something like this can be done by manipulating `sys.modules` so that the lookup won't fail, but I don't know if that has any unexpected side effects.

**Comment by PistonMiner** [comment]
I quickly implemented Qt6 compatibility in bbb47f0 for now. I'll look into the fancier alternative some time in the future.

**Comment by psifertex** [comment]
Yup, works for me, but glad it's resolved either way.

Screen Shot 2021-10-17 at 9 02 04 PM

**Comment by psifertex** [comment]
I tried on a Python 3.8 on MacOS though, there's a chance that older versions of Python can't do it?  ¯\_(ツ)_/¯

**Comment by PistonMiner** [comment]
Looking at that screenshot, assuming I'm understanding you correctly, you typo'd `PySide6` as `PySidey6` and it's still importing fine, so it seems like that first import statement is irrelevant? If I had to hazard a guess, perhaps you have some version of PySide6 installed in that Python environment, and that's what it's importing from? Or am I misunderstanding you entirely here?

**Comment by psifertex** [comment]
🤦‍♂️

This is why I shouldn't computer on the weekend... 😛 

Though now I'm confused why my stable build has both 6 and 2, that.... doesn't seem good.

**Pull request closed without merging**
